on:
    push:
      branches:
        - main
  
name: Deploy to ECR

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: sa-east-1
                
            - name: Restart ECS Instance
              run: aws ecs update-service --cluster minecraft --service mc_server --force-new-deployment --region sa-east-1
